### ISSUE TITLE
Graal Native image with Docker doesn't work as described in docs

### ISSUE THREAD

**Issue by bambulin** [micronaut-guides/creating-your-first-micronaut-app#7]
Dockerfile presented in section 8.3 on your guide page https://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html creates container that doesn't work. 
It displays "permission denied" error because the entrypoint points to directory and not the executable binary. When this is fixed the container doesn't work either and shows error of missing linked libc library.

**Comment by coffee4dev** [comment]
I second this.
What I did:
 * changed last line to `ENTRYPOINT ["/app/micronautguide/micronautguide", "-Xmx68m"]`
 * added `RUN apk add --no-cache libstdc++` just before the last `ENTRYPOINT` line

Afterwards, I was able to run it finally, albeit not without warnings - this one was printed twice:
`/app/micronautguide/micronautguide: /usr/lib/libstdc++.so.6: no version information available (required by /app/micronautguide/micronautguide)`

I used graalvm-ce-java8-19.3.1.

**Comment by ilopmar** [comment]
I've updated to guide to GraalVM 19.3.1 and fixed the scripts.
