### ISSUE TITLE
Gradle test execution results in dependency injection error 

### ISSUE THREAD

**Issue by modev** [micronaut-guides/creating-your-first-micronaut-app#8]
Hello, 
I'm trying to follow the [Creating your first Micronaut app guide](https://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html).
I've installed the CLI according to the documentation and used it to generate a project using default settings using
```
mn create-app com.modev.helloworld
```
Since I'm using IntelliJ, I also enabled the annotation processor. I followed along the guide and got the `/hello` endpoint working as expected. Executing the server and requesting the endpoint returns the Hello World in plaintext.
Following the guide further, I also implemented the test as shown in the guide. When executing the test using the command provided in the guide as well, I receive the following test output:
```
HelloWorldControllerTest > testHello() FAILED
    io.micronaut.context.exceptions.DependencyInjectionException at ClientScope.java:97

1 test completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```
I expected this to work, given that I cannot see any issues with the code, especially since it basically matches the one provided in the getting started guide. I haven't changed anything in the build.gradle file or elsewhere.
My full test code looks as follows
```java
package com.modev;

import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.RxHttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@MicronautTest
public class HelloWorldControllerTest {

    @Inject
    @Client
    RxHttpClient client;

    @Test
    public void testHello() {
        HttpRequest<String> req = HttpRequest.GET("/hello");
        String body = client.toBlocking().retrieve(req);
        assertNotNull(body);
        assertEquals("Hello World!", body);
    }

}
```
I'm using JRE 8 and JDK 11 (GraalVM) (see console output) on Windows 10 64-Bit
```
java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

Is this a general issue or have I messed up somewhere?

**Comment by sdelamo** [comment]
Hello @modev 

I am not sure what is the error your are seeing. If you clone the repo you can see the working at the complete folder. You should be able to execute the tests with `./gradlew test` or you could run the app with `./gradlew run`. 

Please, if you have an example with a reproducible example  reopen the issue. 

Thanks
